version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: esphome-config-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - esphome-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: esphome-config-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - esphome-network

networks:
  esphome-network:
    driver: bridge

volumes:
  backend_data: